/* Generated by parena build -- VS0 domain 3, do not edit by hand. */
#include "parena_runtime.h"
#include <string.h>
#include <stdint.h>
#include <stdlib.h>
#include <math.h>

int gear_max_x100(int);
int on_racer_bike_gear_shift(int, int);

int gear_max_x100(int gear __attribute__((unused))) {
    if ((gear == 1)) {
    return 120;
    } else {
    if ((gear == 2)) {
    return 200;
    } else {
    if ((gear == 3)) {
    return 270;
    } else {
    if ((gear == 4)) {
    return 330;
    } else {
    return 380;
    }
    }
    }
    }
}

int on_racer_bike_gear_shift(int gear __attribute__((unused)), int speed_x100 __attribute__((unused))) {
    if (((gear < 5) && (speed_x100 > ((gear_max_x100(gear) * 92) / 100)))) {
    return (gear + 1);
    } else {
    if (((gear > 1) && (speed_x100 < ((gear_max_x100((gear - 1)) * 55) / 100)))) {
    return (gear - 1);
    } else {
    return gear;
    }
    }
}

